export const habilities = [
    {id: 1,
    name: 'Javascript',
    designation: 'Advanced',
    image: '/assets/Habilities/hab-javascript.png'},
    {id: 2,
    name: 'Python',
    designation: 'Intermediate',
    image: '/assets/Habilities/hab-python.png'},
    {id: 3,
    name: 'Databases',
    designation: 'Intermediate',
    image: '/assets/Habilities/hab-database.png'},
    {id: 4,
    name: 'Git',
    designation: 'Advanced',
    image: '/assets/Habilities/hab-git.png'},
    {id: 5,
    name: 'Excel',
    designation: 'Advanced',
    image: '/assets/Habilities/hab-excel.png'},
  ]