export const social = [
    {id: 1,
    name: 'LinkedIn',
    designation: 'Advanced',
    image: '/assets/Social/Social-linkedin.png'},
    {id: 2,
    name: 'Github',
    designation: 'Intermediate',
    image: '/assets/Social/Social-github.png'},
    {id: 3,
    name: 'Instagram',
    designation: 'Intermediate',
    image: '/assets/Social/Social-instagram.png'},
    {id: 4,
    name: 'Curriculum Vitae',
    designation: 'Intermediate',
    image: '/assets/Social/Social-cv.png'},
  ]